server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_project?createDatabaseIfNotExist=true
    username: root
    password: nisal

  jpa:
    hibernate:
      ddl-auto: create